Modified setup script to be smarter and more forgiving

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,47 +1,79 @@
 #!/bin/sh
 
-is_linked() {
+error() {
+   echo "error: $*" >&2
+}
+
+is_same_file() {
    local source="$(readlink -f $1)"
    local target="$(readlink -f $2)"
 
-   if [ "${source}" != "${target}" ]; then
-      return 1
-   fi
+   # Check if it is a relatve link
+   [ -z "${source}" ] && source="$(readlink -f $(dirname $2)/$1)"
+
+   # Return with an error if source or target is invalid
+   [ -z "${source}" -o -z "${target}" ] && return 1
+
+   [ "${source}" != "${target}" ] && return 1
+   return 0
 }
 
 link_file() {
-   [ -z "$2" ] && return
-   [ -d "$2" ] && return
-   [ "$2" = "${Basename}" ] && return
-
-   local source="$1/$2"
-   local target="${HOME}/$2"
+   [ -z "$3" ] && return 12
+   local targetdir="$1"
+   local sourcedir="$2"
+   local filename="$3"
+   local target=$1/$3
+   local source=$2/$3
 
    if [ -L "${target}" ]; then
-      if is_linked "$source" "$target"; then
+      if is_same_file "${source}" "${target}"; then
          # Target already linked, do nothing
          return
       fi
-         # Target linked some where else
-         echo "  ${target} - Linked to '$(readlink ${target})', skipping!"
+      if [ -r ${target} ]; then
+         error "'${target}' already linked ('$(readlink ${target})'), skipping!"
          return
-   fi
-
-   if [ -f "${target}" ]; then
-      # Target file already exists
-      echo "  ${target} - Is a file, skipping!"
+      fi
+      # Remove broken link
+      rm "${target}"
+   elif [ -f "${target}" ]; then
+      error "'${target}' exists and is a file, skipping!"
       return
    fi
 
-   echo "  ${source} -> ${HOME}"
-   ln -s "${source}" "${HOME}"
+   echo "  linking '${source}' -> '${targetdir}'"
+   ln -s "${source}" "${targetdir}"
+}
+
+list_dir() {
+   find "$1" -maxdepth 1 -type f -printf "%f\n"
+}
+
+setup_dotfiles() {
+   echo "Setting up links in ~/"
+   Files=$(list_dir ${Dotdir})
+   for File in ${Files}; do
+      [ "${File}" = "${Basename}" ] && continue
+      link_file "${HOME}" "${Basedir}" "${File}"
+   done
+}
+
+setup_subdir() {
+   local subdir="${Dotdir}/$1"
+
+   [ -d "${subdir}" ] || return 1
+
+   echo "Setting up links in ~/${subdir}"
+   Files=$(list_dir ${subdir})
+   for File in ${Files}; do
+      link_file "${HOME}/bin" "../${subdir}" "${File}"
+   done
 }
 
 Basename=$(basename "$0")
 Basedir=$(dirname "$0")
-Dotfiles=$(ls -a ${Basedir})
+Dotdir="${Basedir}"
 
-echo "Setting up symlinks.."
-for Dotfile in ${Dotfiles}; do
-   link_file "${Basedir}" "${Dotfile}"
-done
+setup_dotfiles
+setup_subdir bin
